### ISSUE TITLE
The link to https://github.com/weixsong/lunr-languages is broken!

### ISSUE THREAD

**Issue by kaijauk** [weixsong/elasticlunr.js#104]
The link to https://github.com/weixsong/lunr-languages is broken! 

I then used https://github.com/MihaiValentin/lunr-languages and now I get the same error as in https://github.com/weixsong/elasticlunr.js/issues/80#

_Originally posted by @kaijauk in https://github.com/weixsong/elasticlunr.js/issues/80#issuecomment-475981001_

**Comment by weixsong** [comment]
@kaijauk , sorry for un-convenience. the repo https://github.com/weixsong/lunr-languages is recovered.
