### ISSUE TITLE
Fuzzy search?

### ISSUE THREAD

**Issue by jloveric** [weixsong/elasticlunr.js#11]
Is there fuzzy search capability in elasticlunr?

Thanks,

John

**Comment by weixsong** [comment]
Hi, @jloveric , sorry, currently elasticlunr.js does not support fuzzy search, but it could support expand the query tokens and then search all the expanded tokens. 
Such as, you query with "buy apple", then if you set expand=True, buy will be expanded all possible tokens with buy as prefix, buying, buyer, buys, and apple will be expanded to apples, applet, 
Sorry for the inappropriate examples, I'm not good at english, I hope you could get my idea.

**Comment by playground** [comment]
Will fuzzy search be supported?
