### ISSUE TITLE
Delegate or add maintainers

### ISSUE THREAD

**Issue by srenauld** [weixsong/elasticlunr.js#111]
In light of how a PR took 8 months to be accepted, and how the library published on npm is a whole 3 years behind what it is on here, I think it might be time to add additional maintainers on both github and npm in order to ease things up and allow more people to contribute to what should be a lively project. 

I would be more than happy to shoulder at least part of that burden as I use elasticlunr in production on two projects, and authored about half of the rewrite that just went through the latest PR. I'm also pretty sure I would not be the only one.

**Comment by smurrayatwork** [comment]
@weixsong Thoughts on this? This is used on production for many https://www.gatsbyjs.org/ websites.

Gatsby Plugins:
- https://github.com/gatsby-contrib/gatsby-plugin-elasticlunr-search (over 11k downloads)
- https://github.com/andrew-codes/gatsby-plugin-elasticlunr-search

**Comment by weixsong** [comment]
@srenauld , I have added you to the Collaborators, please try it. And really thanks very much for the contribution.

**Comment by srenauld** [comment]
@weixsong Thank you for the change, that is one positive step forward!

As I see it, there are a few ways to make this mostly self-managing, but it will require you to do a few more things. They don't have to be done right now.

Step 0 is proper gitflow, which I can set up myself. As I doubt we will need to backport changes across multiple versions, I am pretty confident we can keep a single development and staging branches, and as such, the flow will be from dev to staging, staging to master in order to release.

The first is continuous integration, which we don't have at the moment, but the PR I threw at this project 9 months ago allows this (as I changed the underlying test framework to something most CI/CD tools understand). I will get to making a travis configuration and checking whether it fits our needs to validate a build.
While doing this, I will include e2e tests such as a basic gatsby setup, as the gatsby community relies on this to function.

The added bonus of both changes is that, if they're in and gitflow is obeyed, we can then deploy to npm automatically when something happens on master.

**Comment by weixsong** [comment]
@srenauld , great, as I haven't been working on JS for a long time, I do not know what it the best way to develop the JS project. You could do whatever you think is right and make the repo popular again. :)

Thanks again.
