### ISSUE TITLE
expand doesn't work with bool: 'AND'

### ISSUE THREAD

**Issue by mhalle** [weixsong/elasticlunr.js#13]
Looks like prefix search (expand: true) doesn't work when bool: 'AND'.

I think the behavior should be that AND should apply to the user's tokens, not the expanded ones.

**Comment by weixsong** [comment]
Yes, you are right, this is intended behave.
Because most of the time user won't know what a token will be expanded to, so we don't want to apply AND operation to expanded tokens, if so, that would make the output a little weird and difficult to debug.

**Comment by mhalle** [comment]
Thanks.

Let me clarify. What I would like to do is to prefix search with the results of each prefix and together.  

For example:
"le ri bot"  would expand to: (lemon OR letter) AND (right OR riddle) AND (bottle OR bottom)
This is the behavior I would expect from {expand: true, bool: "AND"}.  

What seems to happen now is that the "AND" overrides the "expand", and no prefix searching occurs.

Does that make my issue clearer?

**Comment by weixsong** [comment]
Yes, thanks for your idea, it's a good idea, I think I could support this feature in the future.
Or if you have time, you could change the code and submit a pull request.

Thanks very much for brilliant idea.
