### ISSUE TITLE
Highlighting feature

### ISSUE THREAD

**Issue by vladimiry** [weixsong/elasticlunr.js#15]
Would be great to have such feature. In any form, either highlighted matched words (configurable to which elements/tags to wrap) or just positional information of matched tokens (so highlighting itself could be done outside of the `elasticlunr.js`).

**Comment by weixsong** [comment]
Hi, @vladimiry , thanks very much for your idea. 
Your idea is great, but currently our data structure doesnot support record the position of each word, that means increase the index size. But your idea is really brilliant.
In the future I will add support for your idea.

**Comment by xcv58** [comment]
Any update on this feature request?
