### ISSUE TITLE
support chinese

### ISSUE THREAD

**Issue by malun666** [weixsong/elasticlunr.js#21]
## Thanks for this great repo!
Support [Chinese segment](https://github.com/leizongmin/node-segment) will be great!
thanks again.

**Comment by weixsong** [comment]
We could create another branch that integrate Chinese tokenizer as default tokenizer in next release.

**Comment by andyhu** [comment]
Is it implemented now?

**Comment by andyhu** [comment]
What I'm thinking is to provide a plugable system, if a developer really need a Chinese tokenlizer, then it could be done by some way like this:
```js
elasticlunr.setTokenlizer(require('nodejieba');
```
And if it's not specified, then use the default one.
What do you think?

**Comment by weixsong** [comment]
@andyhu , yes, I agree with you.

<code>nodejieba</code> is a good package for Chinese tokenization. 
But one big issue is that this [elasticlunr](http://elasticlunr.com/) is supposed to be used in browser for offline.
So my concern is that if we support Chinese, we need to add the package into elasticlunr, and make it a isolated package that could be used in elasticlunr even without network connection.
