### ISSUE TITLE
Bulk Add

### ISSUE THREAD

**Issue by indolering** [weixsong/elasticlunr.js#25]
I'm loading up a database with ~30K documents and adding them via a for loop takes ~3 seconds on a desktop (which would be crazy slow on a phone).  I was thinking of adding an `addDocs(Array)` function that would use setTimeout to load everything in a non-blocking manner.  However, I was hoping there might be a faster method....

**Comment by weixsong** [comment]
Hi @indolering , thanks for your idea.
Yes, it is important to setup some timeout threadhold or non-blocking manner.

Usually, user will build index offline, and then use the build index in mobile device, this means that elasticlunr only need to load index but not the documents and do not need to build the index at runtime.

But your idea is still very good, we should support non-blocking index loading.

**Comment by weixsong** [comment]
Hi @indolering , I'm not familiar with Nodejs or javascript, if you are good at nodejs/javascript, you are welcome to contribute some code that make the index load non-blocking way.
Thanks very much.

**Comment by indolering** [comment]
@weixsong Ahh, I didn't realize that you are supposed to build the index offline first.  Perhaps you should update the docs outlining this procedure?

Given this, it isn't worth the effort to do non-blocking.  Just loop over `addDoc` as normal.

P.S. Thank you very much for elasticlunr and maintaining english docs.

**Comment by weixsong** [comment]
@indolering , good suggestion, I didnot notice that I need to outline the steps. Because for people knowing search theory, they will build index offline by default. But most of people do not know the theory of search, so it indeed necessary to outline the the usage steps.
