### ISSUE TITLE
Faceting / aggregation

### ISSUE THREAD

**Issue by ludoo0d0a** [weixsong/elasticlunr.js#26]
Do you think, like Solr or ES, faceting (or aggregation) is something feasible in a such lightweight search engine ?

**Comment by weixsong** [comment]
@ludoo0d0a , thanks for your idea. I think aggregation is feasible, but my purpose is to make elasticlunr.js a light-weight search engine that run in browser or node.js project, so I think if user want to use a full function search engine, they could find lots of powerful search engine such as Solr or ES. But if they want to use some light search engine, then elasticlunr.js is what they want.
So I'd like to keep elasticlunr.js as light as possible.
