### ISSUE TITLE
Having external document store instead of default

### ISSUE THREAD

**Issue by codeforgeek** [weixsong/elasticlunr.js#29]
Hi guys,

Great job with this module.

Right now, document store is in memory and we are loading index from files all at once.

What i working on is to add that in external document storage for same so that i can add lots of index without having out of memory issue.

Here is my concern:

Right now we are adding all the links in this format:
{"link": {attr key value}}

which is great for one site, i want to add multiple site in the elastic lunr at Server side and want to share the common front-end across various sites and while doing search I dont want to fetch content of abc.com [eg] even though keyword match because user is searching on pqr.com.

What you guys suggest about optimal schema for same considering less code changes in the module.

**Comment by weixsong** [comment]
Hi @codeforgeek ,  Sorry for the late reply.

I'm not quite understand your issue.
But according to my understanding, with Elasticlunr.js you could setup it that do not store source documents, this means you just build index and store index.

And, for another issue, that return only user fetched document fields, I think currently Elasticlunr.js will only return document ID & score, then you could retrieve document by ID, this require user design their documents storage themselves.

But if you want to use powerful search engine, I think elasticsearch is a better choice.

**Comment by codeforgeek** [comment]
"And, for another issue, that return the only user fetched document fields, I think currently Elasticlunr.js will only return document ID & score, then you could retrieve a document by ID, this requires user design their documents storage themselves."

-- I am working on same. I will store the indexes which are docInfo object in memory as it is for faster search but will store docs i.e docs object in the persistent database because of memory issue. Right now docs are key value object and I need to modify same to make it work.

What I wanted from you is a recommendation and the best way to do it since you wrote this :) ElasticSeach is of course something I wanna do but in future.
