### ISSUE TITLE
"Token Expandation" causes JavaScript error

### ISSUE THREAD

**Issue by bushd** [weixsong/elasticlunr.js#3]
Hi, when I enable **Token Expandation** by adding the _expand: true_ option for a search on the index, I get the following error message in chrome: 
 "Uncaught TypeError: Cannot read property 'length' of undefined" (elasticlunr.js:948)

Looking at the source, this would be the following code:
```javascript
elasticlunr.Index.prototype.coordNorm = function (scores, docTokens, n) {
  for (var doc in scores) {
    var tokens = docTokens[doc].length;
    scores[doc] = scores[doc] * tokens / n;
  }

  return scores;
};
```

And indeed, _docTokens[doc]_ is undefined. The reason is, that _docTokens_ itself is already an empty object. It is defined in the _fieldSearch_ function, but in case of a penalty nothing is added.

For me it looks like _fieldSearchStats_ should always be called in _fieldSearch_, not only if there is no penalty - but I am not sure about the intention of this code.

Do I miss something? Do I need to add anything to the initialisation of elasticlunr?

**Comment by weixsong** [comment]
Hi, @bushd , sorry for this late reply, I was really busy for a long time.
Thanks for reporting this issue, I will fix this issue ASAP.

**Comment by weixsong** [comment]
Hi, @bushd , I've fixed this issue.

fieldSearchStats() is used to record how many original query token appears in the retrieved documents,  when doing coordNorm, I'm trying to ranking documents with more original query tokens higher that documents with less original query tokens.

When user set expand to true, expanded tokens should not be added into docTokens, I think this will pollute coordNorm.

But my code definitely has bug, for docId in scores, part of the docId are retrieved by expanded tokens, so these docId are not in docTokens, so I need to verify if that doc is in docTokens.

Thanks very much for reporting this issue.

```python
elasticlunr.Index.prototype.intersect = function (scores, docTokens, n) {
  var res = {};

  for (var doc in scores) {
    if (!(doc in docTokens)) continue;
    if (docTokens[doc].length == n) {
      res[doc] = scores[doc];
    }
  }

  return res;
};
```
