### ISSUE TITLE
Searching a multiple word term in a field

### ISSUE THREAD

**Issue by kzachos** [weixsong/elasticlunr.js#31]
Excellent work and thanks for making it available. I have one issue with regards to search terms that consist of multiple words, i.e. compound terms. For instance, how would I search for 

'public transport' OR car 

without getting results that match either public or transport rather the whole term. Is this currently possible?

Thanks

**Comment by weixsong** [comment]
Hi @kzachos , currently Elasticlunr.js does not support your requirement, because the tokenizer will separate 'public transport'.

But this is really interesting and seems that lots of user need this feature, will support it in future.

**Comment by krazylearner** [comment]
@weixsong i need same feature but cant we just join multiple words with spaces and search for it .
For example one could do something like

`
var words = ['cat ','camel'].join(' ');
var result = index.search(words);
console.log(result);
`
will this work ?
will i get  those results which may contain cat or camel ?

Thanks

**Comment by weixsong** [comment]
Hi, @krazylearner , yes, you could do it as your code. but more simple you could just search "cat camel", it's the same way.

**Comment by krazylearner** [comment]
@weixsong thanks for your reply . In my case i get cat and camel as tags in array so i have to join them and fetch results which may contain 'cat' OR 'camel'
