### ISSUE TITLE
Word association dictionary

### ISSUE THREAD

**Issue by yangwen2** [weixsong/elasticlunr.js#32]
Awesome work!

Would it possible to add mechanism to support word association? This could be a map that each implementation would need to manually configure and maintain.  To build up a rich word association map that specific to the domain of the use case.  It would introduce an additional dimension of usefulness beyond explicit token match.

Of course, I could just create this outside of the elasticlunr library and have it the word association map augment the search input accordingly.

**Comment by weixsong** [comment]
Hi, @yangwen2 , good idea, thanks for this great idea. I will try to support association dictionary in future release.
