### ISSUE TITLE
saveDocument(false) and index.documentStore.docs

### ISSUE THREAD

**Issue by gpakosz** [weixsong/elasticlunr.js#34]
Hello,

When `saveDocument()` is set to `false`, can't you drop `index.documentStore.docs` entirely by assigning it an empty object?

Thanks

**Comment by weixsong** [comment]
Hi @gpakosz , good idea, I'm not familiar with javascript. Thanks for your idea. And you're welcome to contribute code into Elasticlunr.js. :)

**Comment by gpakosz** [comment]
Uh excuse me but, you're the author of a Javascript library but you're saying you're not familiar with Javascript?
