### ISSUE TITLE
No results when only entering first couple of letters

### ISSUE THREAD

**Issue by adibsaad** [weixsong/elasticlunr.js#5]
This is obviously me not understanding the algorithms in place, but when you search for the first few letters in a index, you get no results when it seems like you should..

```
var index = elasticlunr(function(){
    this.addField('name');
    this.setRef('id');
});

index.addDoc({id: 1, name: 'Elvis Presley'});
index.addDoc({id: 2, name: 'Queen Victoria'});
index.addDoc({id: 3, name: 'Plato'});
index.addDoc({id: 4, name: 'Angelina Jolie'});
index.addDoc({id: 5, name: 'Abraham Lincoln'});

// no results
index.search('p');
index.search('pl');
index.search('pla');
index.search('plat');

//result
index.search('plato');
```

Was hoping if someone could comment on this.

**Comment by weixsong** [comment]
Hi, @adibsaad , thanks for pointing out this issue, currently elasticlunr will not support token expandation by default.
If you want to increase Recall, you could set expand to true by adding a search configuration
```javascript
index.search('p', {expand: true});
```

**Comment by marvinjude** [comment]
Just what i was looking for!
