### ISSUE TITLE
sorting by both relevance and 2nd numeric field like timestamp

### ISSUE THREAD

**Issue by paultman** [weixsong/elasticlunr.js#7]
I've looked though docs for elasticsearch and there it looks like a secondary sorting field can be added, is that also possible with elasticlunr?  I'd like to sort results by both relevancy and a timestamp.  I could manually do this once I have the result set however if it's already built in, even better.

**Comment by weixsong** [comment]
Yes, good idea, we could pass in an sort function to search API, and then use customized sort function to sort all the retrieved documents. 
How do you think about my idea?

**Comment by weixsong** [comment]
@paultman , thanks very much for your idea, after some consideration, I think I'd better keep Elasticlunr.js as simple as possible, that user could use it without any trouble, user don't need to get understand how full-text search works. Thanks very much.

**Comment by paultman** [comment]
Hello @weixsong thanks for your feedback.  I agree with you, and infact it was easy enough to sort once I got the results back.  It's actually more efficient, as the result set is a much smaller set then the entire sample.  Even only adding the extra sorting field to each element when preparing the index would have been slower.

Great work on the library, i'm using it and am extremely happy I don't have to create something similar myself :)  

Thanks for your contributions!
-Paul
