### ISSUE TITLE
Search multiple fields into one query

### ISSUE THREAD

**Issue by JohannGillium** [weixsong/elasticlunr.js#9]
Hello,

I came to Elasticlunr from Lunr because I was interested by the functionnalities regarding the search by field, and I wasn't disappointed, it works really fine, and Elasticlunr, as the original Lunr search engine, is a great piece of work, and thanks for developing it. But still for the website that I'm working on, I would love to implement an "advanced search" page, with the possibility for the user to search for different strings in multiple fields during the same query, to find the item which fulfills all conditions. Well, not many fields, since it is a client-side search engine, but Elasticlunr works so fast that it looks like it could certainly handle one query with three different parameters for different fields.

  For now, if I understand correctly, we can query the same words, so in the example below, "Oracle dabase profit" would be searched in Title and body. 

```
index.search("Oracle database profit", {
    fields: {
        title: {boost: 2},
        body: {boost: 1}
    },
    boolean: "OR"
});
```

And it would be great if we could search for THE item with "Database" in its title, and "Oracle profit" in its body, for instance. Having one function to handle that case is the issue that I want to raise, if it hasn't been already dismissed as technically impossible.

### How to implement this with the already built-in functions

Certainly, there must be a way of already doing that with the built-in functions already implemented. Here we leave the general issue to broach one difficulty that I have to implement this (but I think it may be of interest for others Elasticlunr users, if somebody could help me to solve it and share the solutions).  I was thinking of two distinct queries ( query1 = "database" in title, query2 = "Oracle profit" in body), storing the results into arrays, and comparing thereafter the two (or more if searching into more fields) arrays of results to find matching values in this arrays. 

My issue is that, as a beginner in JS, I don't succeed to make the fieldSearch function working. The final goal is, for each selected field in a form, to call a function which search for the string in this particular field, and then compare the three arrays of result to find the matching values, and therefore the item which fullfills alls the condition of the search. 

I have this, which is supposed to take the query, and the field selected by the user in a dropdown list, and pass them as parameters to the fieldSearch function, display the result of the search.

```
 $(document).ready(function() {
       $('button#search').on('click', function () {
             var query = $("input#keyword-search").val();
             var SelectedField = $('#optgroupDublinCore option:selected').text();
             var queryTokens = elasticlunr.index.search.pipeline.run(elasticlunr.tokenizer(query));
             var result = index.fieldSearch(queryTokens, SelectedField); 
             var resultdiv = $('#results');
              resultdiv.append('<p class="">Found '+result.length+' result(s)</p>');
              for (var item in result) {
	           var ref = result[item].ref;
	           var searchitem = '<div class="result"><p><a href="{{ site.baseurl    }}'+store[ref].link+'">'+store[ref].title+'</a> by '+store[ref].author+'type :'+store[ref].type+'</p></div>';
    alert(searchitem);
    resultdiv.append(searchitem);
  }})})
```

But I get that error "Uncaught type error : cannot read property run of undefined". Obviously it had to do with the queryTokens variable, and the keyword "this" in this.search.pipeline.run(elasticlunr.tokenizer(query));, which I have replaced by "elasticlunr.index.search", assuming that it was the object referred by "this". 

If someone can help me with this, I would really appreciate ! And it could be of use for others, maybe to add as an example of implementation in the doc., since multiple fields queries are an interesting feature.

**Comment by weixsong** [comment]
Hi @JohannGillium , thanks very much for bring this idea.
I could add a function that support field search about different query for different field.

Currently, regarding your question,
in you code, please change your code:
```javascript
var queryTokens = elasticlunr.index.search.pipeline.run(elasticlunr.tokenizer(query));
```

to :
```javascript
var queryTokens = elasticlunr.pipeline.run(elasticlunr.tokenizer(query));
```

pipeline is not an instance function, it's a class function, you just need to use it from elasticlunr namespace directly.

Take a try and any problem please let me know. 
Thanks again.

**Comment by JohannGillium** [comment]
Hi @weisong, thank you very much for your reply, and also for your help
about my problem. Unfortunately, your solution didn't work in my case, and
I have still one error in my console, which says basically that it cannot
use the function pipeline from 'undefined'. It is like the name space
elasticlunr wasn't recognized, which doesn't make sense since in the same
context I can run a basic search query using index.search.

I will add more details tomorrow on this case, after my own investigation.
(Sorry for not having responded earlier, I was in a trip this last days).

Best,

**Comment by weixsong** [comment]
Hi, @JohannGillium , sorry to mis-guide you, actually you could use the following code
```javascript
index.pipeline.run(elasticlunr.tokenizer('hello world'))
```

I have tried, this will work.
Regards,

**Comment by JohannGillium** [comment]
Hi, @weixsong, it works perfectly, thank you very much ! I should have thought of using .index.

I'm struggling since yesterday with another issue, because the fieldSearch function expects a config parameter, and would not take automatically - as the search function does - the default configuration. So when I use : 

`var result = index.fieldSearch(queryTokens, fieldName); `

I've got this error : "Uncaught TypeError: Cannot read property 'title' of undefined" with a link to this line of elasticlunr (def of fieldSearch function) :  var booleanType = config[fieldName].bool. So I figured the error occured because of the lack of configuration.

To fix this, I tried to provide a default configuration as parameter to the searchField function. Like this : 
  `var config = {fields: {title: {boost: 1, bool: "OR", expand: false }}}`
`var result = index.fieldSearch(queryTokens, fieldName, config); `

But it gives this error : Uncaught TypeError: Cannot read property 'bool' of undefined.

It would be nice if we could have the fieldSearch function use the default configuration. But I really don't know how I could do that. I tried to do something like : 

`var config = configuration.buildDefaultConfig(index.fields);`
But it didn't work neither. Again an error "Cannot read property 'buildDefaultConfig' of undefined". I tried also with "elasticlunr.configuration" etc... but it didn't work neither.

If you have a clue of what is the problem, I certainly would appreciate. Thanks again for your attention !

**Comment by weixsong** [comment]
Hi, @JohannGillium , thanks for feedback.
In order to use fieldSearch function directly, you need to provide a Configuration object as parameter,
use the following code to generate an instance of Configuration:
```javascript
  var configStr = null;
  if (userConfig != null) {
    configStr = JSON.stringify(userConfig);
  }

  var config = new elasticlunr.Configuration(configStr, this.getFields()).get();
```

be careful about the code, this.getFields() only work in the context of index, so you could change it to an array of field names.

Any issue please tell me.

**Comment by JohannGillium** [comment]
Hi, @weixsong, it worked very well, thank you so much ! Now that I am able to perform a query on a single field, it should be easy to write the code to have differents queries for differents fields, store results of each query in arrays, and check for matching values. As soon as it will be done, I will post here my code.

Thank you again,

Best,

**Comment by jflheureux** [comment]
Hi @weixsong. I have the same requirement of finding the intersection of multiple search result arrays for a project. Is this feature started on your side? I could probably work on it and send you a pull request.

**Comment by playground** [comment]
@jflheureux is this feature [#30](https://github.com/weixsong/elasticlunr.js/issues/30) now available?

**Comment by jflheureux** [comment]
@playground You can see my implementation here: https://github.com/jflheureux/elasticlunr.js/commit/e9b14bbe5d0d6f3b8852e6a8248dae0d3dd5bfa3
It was not added as a pull request because it was changing the API. I use this code in production without any problem.
