### ISSUE TITLE
Question on React-Native usage

### ISSUE THREAD

**Issue by Jayasagar** [weixsong/elasticlunr.js#97]
Hi,

Thank you so much for such an amazing work! Need clarification on using React-Native for mobile apps!

Is this library compatible with React-Native?

Thanks
Jay

**Comment by charles-merlinguides** [comment]
It's pure JS so it can work with React-Native, Angular, Vue...etc.

For instance, I've used it with AngularJS and Electron together.

**Comment by Jayasagar** [comment]
Thank you @charles-merlinguides for responding so quickly 👍  
I was wondering what would be storage location. I think produced whole indexed content as a JSON which I can save it on Mobile or reload for offline.

Let me give a try!

Thanks

**Comment by charles-merlinguides** [comment]
So, storage isn't available out of the box as everything is in memory. To get around this you can basically copy the Object and save it. What I do is I store it as a .JSON object on the users machine, however you could store it any way you want really.
